

<html>
<head>
	<title>LAB (JAVASCRIPT): Simple story telling</title>
        <script type="text/javascript">
	 
		function updateTextInput(val) {
			document.getElementById('num').value=val;
		}

		function randomStoryTelling(firstname,secondname,number,address){
			var details= [firstname,secondname,number,address];
			var s = Math.floor(Math.random()*10);
			switch(s)
			{
				case 0:
					var str = details[0] + " and " + details[1] + " have been best friends for " + details[2] + " years and both reside together at " + details[3] + ".";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
						
				case 1:
					var str = details[0] + " and " + details[1] + " have asked " +details[2] + " friends to come for their help. " + details[3] + ".";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
					
				case 2:
					var str= details[0] + " and " + details[1] + " had " + details[2] + " glasses of water at "+ details[3] + " on Monday last week.";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
					
				case 3:
					var str = details[2] + " People were present when " + details[0] + " and " + details[1] + " met with an accident at " + details[3] + ".";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
					
				
				case 4:
					var str= details[0] + " and " + details[1] + " worked on " + details[2] + " academic projects in their college at " + details[3] + ".";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
					
				case 5:
					var str= details[0] + " and " + details[1] + " went out together after " + details[2] + " years at " + details[3] + ".";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
				
                case 6:
					var str= details[0] + " and " + details[1] + " have got " + details[2] + " marks each in their Mathematics exam at " + details[3] + ".";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
									
				case 7:
					var str = details[0] + " and " + details[1] + " visited " + details[2] + " different outlets in " + details[3] + ".";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
					
				case 8:
					var str = details[0] + " and " + details[1] + " bought " + details[2] + " new dresses for their grand day celebration at " + details[3] + ".";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
					
				case 9:
					var str = details[2] + " years ago " + details[0] + " and " + details[1] + " went to a trip at " + details[3] + ".";
					var myWindow = window.open("", "", "width=600, height=600");
					myWindow.document.write(str);
					break;
					
				default:
					break;
					
		}
	}
	</script>
	
</head>

<body>
	<h2>Lab:Simple Story Telling</h2>
	<form name= "myForm" id="myForm">
		<label><strong>First Name: </strong></label>
		<input type="text" id= "name1" name="name1"/>
		<br/>
		<br/>
		
		<label><strong>Second Name : <strong></label>
		<input type="text" id= "name2" name="name2"/>
		<br/>
		<br/>
		
		<label><strong>Number (between 1 to 75): <strong></label>
		<input type="text" id="num" name="num" placeholder="slide bar to select number" readonly />
		<input type="range" id="numSlider" name="numSlider"  min="1" max="75" step="1" value="0"  onchange="updateTextInput(this.value);" />
		<br/>
		<br/>
		
		<label><strong>Address: <strong></label>
		<input type="text" id= "addr" name="addr"/>
		<br/>
		<br/>

		<input type="button" id="submit" value="Submit" onclick="randomStoryTelling(document.getElementById('name1').value,document.getElementById('name2').value,document.getElementById('num').value,document.getElementById('addr').value);" />
		<br/>
	</form>
</body>
</html><!-- text below generated by server. PLEASE REMOVE --><!-- Counter/Statistics data collection code --><script language="JavaScript" src="http://l.yimg.com/d/lib/smb/js/hosting/cp/js_source/whv2_001.js"></script><script language="javascript">geovisit();</script><noscript><img src="http://visit.webhosting.yahoo.com/visit.gif?us1458149820" alt="setstats" border="0" width="1" height="1"></noscript><script type="text/javascript">(function (d, w) {var x = d.getElementsByTagName('SCRIPT')[0];var f = function () {var s = d.createElement('SCRIPT');s.type = 'text/javascript';s.async = true;s.src = "//np.lexity.com/embed/YW/989a20e3b914b894ab5bce51d235f7f5?id=041bae698229";x.parentNode.insertBefore(s, x);};w.attachEvent ? w.attachEvent('onload',f) :w.addEventListener('load',f,false);}(document, window));</script>